# Generated by Django 4.1.2 on 2022-10-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_kategori_produk_kategori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='deskipsi',
            new_name='deskripsi',
        ),
    ]
